//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class analogicas : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle1;
        
        private Neo.ApplicationFramework.Controls.Controls.RectangleCF m_Rectangle;
        
        private Neo.ApplicationFramework.Controls.Controls.PolylineCF m_PolyLine;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text8;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group;
        
        private Neo.ApplicationFramework.Controls.Controls.CircularMeterCF m_CircularMeter;
        
        private Neo.ApplicationFramework.Controls.Controls.SliderCF m_Slider1;
        
        private Neo.ApplicationFramework.Controls.Controls.SliderCF m_Slider;
        
        private Neo.ApplicationFramework.Controls.Controls.LinearMeterCF m_LinearMeter;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.AnalogNumeric m_AnalogNumeric;
        
        private Neo.ApplicationFramework.Controls.Controls.PolylineCF m_PolyLine1;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text4;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text6;
        
        private Neo.ApplicationFramework.Controls.Controls.PolylineCF m_PolyLine2;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text5;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group1;
        
        private bool m_Initialized_analogicas;
        
        private Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF brushdynamicsconvertercf1;
        
        public analogicas() {
            this.InitializeComponent();
            this.m_Slider1.ValueChanged += new System.EventHandler(this.m_Slider1_Action_ValueChanged);
            this.m_Slider.ValueChanged += new System.EventHandler(this.m_Slider_Action_ValueChanged);
            this.m_Group1.MouseEnter += new System.EventHandler(this.m_Group1_Action_MouseEnter);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Rectangle {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Rectangle);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter PolyLine {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter>(this.m_PolyLine);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text8 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text8);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.MeterCFAdapter CircularMeter {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.MeterCFAdapter>(this.m_CircularMeter);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter Slider1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter>(this.m_Slider1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter Slider {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter>(this.m_Slider);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter LinearMeter {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LinearMeterBaseCFAdapter>(this.m_LinearMeter);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter AnalogNumeric {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericCFAdapter>(this.m_AnalogNumeric);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter PolyLine1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter>(this.m_PolyLine1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text6 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text6);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter PolyLine2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter>(this.m_PolyLine2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text5 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text5);
            }
        }
        
        private void InitializeComponent() {
            this.brushdynamicsconvertercf1 = new Neo.ApplicationFramework.Common.Dynamics.BrushDynamicsConverterCF();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval1 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval2 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval brushcfinterval3 = new Neo.ApplicationFramework.Common.Dynamics.BrushCFInterval();
            this.m_Ellipse1 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Rectangle1 = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_Rectangle = new Neo.ApplicationFramework.Controls.Controls.RectangleCF();
            this.m_PolyLine = new Neo.ApplicationFramework.Controls.Controls.PolylineCF();
            this.m_Text8 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Group = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_CircularMeter = new Neo.ApplicationFramework.Controls.Controls.CircularMeterCF();
            this.m_Slider1 = new Neo.ApplicationFramework.Controls.Controls.SliderCF();
            this.m_Slider = new Neo.ApplicationFramework.Controls.Controls.SliderCF();
            this.m_LinearMeter = new Neo.ApplicationFramework.Controls.Controls.LinearMeterCF();
            this.m_Text = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_AnalogNumeric = new Neo.ApplicationFramework.Controls.Controls.AnalogNumeric();
            this.m_PolyLine1 = new Neo.ApplicationFramework.Controls.Controls.PolylineCF();
            this.m_Text3 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text4 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Text6 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_PolyLine2 = new Neo.ApplicationFramework.Controls.Controls.PolylineCF();
            this.m_Text5 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Group1 = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_CircularMeter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Slider1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Slider)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LinearMeter)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).BeginInit();
            this.SuspendLayout();
            // 
            // analogicas
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_Ellipse1
            // 
            this.m_Ellipse1.BlinkDynamicsValue = false;
            this.m_Ellipse1.EnabledDynamicsValue = true;
            this.m_Ellipse1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(130)))), ((int)(((byte)(180))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Height = 33;
            this.m_Ellipse1.Left = 67;
            this.m_Ellipse1.Name = "m_Ellipse1";
            this.m_Ellipse1.ScreenOwnerName = "analogicas";
            this.m_Ellipse1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Top = 227;
            this.m_Ellipse1.VisibleDynamicsValue = true;
            this.m_Ellipse1.Width = 85;
            // 
            // m_Rectangle1
            // 
            this.m_Rectangle1.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle1.BlinkDynamicsValue = false;
            this.m_Rectangle1.EnabledDynamicsValue = true;
            this.m_Rectangle1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.Height = 368;
            this.m_Rectangle1.Left = 427;
            this.m_Rectangle1.Name = "m_Rectangle1";
            this.m_Rectangle1.ScreenOwnerName = "analogicas";
            this.m_Rectangle1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle1.StrokeThickness = 3;
            this.m_Rectangle1.Top = 28;
            this.m_Rectangle1.VisibleDynamicsValue = true;
            this.m_Rectangle1.Width = 338;
            // 
            // m_Rectangle
            // 
            this.m_Rectangle.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF();
            this.m_Rectangle.BlinkDynamicsValue = false;
            this.m_Rectangle.EnabledDynamicsValue = true;
            this.m_Rectangle.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.Height = 368;
            this.m_Rectangle.Left = 0;
            this.m_Rectangle.Name = "m_Rectangle";
            this.m_Rectangle.ScreenOwnerName = "analogicas";
            this.m_Rectangle.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Rectangle.StrokeThickness = 3;
            this.m_Rectangle.Top = 0;
            this.m_Rectangle.VisibleDynamicsValue = true;
            this.m_Rectangle.Width = 390;
            // 
            // m_PolyLine
            // 
            this.m_PolyLine.BlinkDynamicsValue = false;
            this.m_PolyLine.EnabledDynamicsValue = true;
            this.m_PolyLine.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(99)))), ((int)(((byte)(116))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine.Height = 51;
            this.m_PolyLine.Left = 133;
            this.m_PolyLine.Name = "m_PolyLine";
            this.m_PolyLine.Points = new Neo.ApplicationFramework.Common.Collections.PointDList(new Neo.ApplicationFramework.Interfaces.PointD[] {
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(40.0781257805173D, 48.4999997971747D),
                        new Neo.ApplicationFramework.Interfaces.PointD(256.500004995311D, 48.4999997971747D),
                        new Neo.ApplicationFramework.Interfaces.PointD(256.500004995311D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D)});
            this.m_PolyLine.ScreenOwnerName = "analogicas";
            this.m_PolyLine.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine.Top = 0;
            this.m_PolyLine.VisibleDynamicsValue = true;
            this.m_PolyLine.Width = 259;
            // 
            // m_Text8
            // 
            this.m_Text8.BlinkDynamicsValue = false;
            this.m_Text8.EnabledDynamicsValue = true;
            this.m_Text8.FontSizePixels = 20;
            this.m_Text8.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text8.Height = 28;
            this.m_Text8.Left = 182;
            this.m_Text8.Name = "m_Text8";
            this.m_Text8.ScreenOwnerName = "analogicas";
            this.m_Text8.Top = 9;
            this.m_Text8.VisibleDynamicsValue = true;
            this.m_Text8.Width = 157;
            // 
            // m_Group
            // 
            this.m_Group.BlinkDynamicsValue = false;
            this.m_Group.Components.Add(this.m_Rectangle);
            this.m_Group.Components.Add(this.m_PolyLine);
            this.m_Group.Components.Add(this.m_Text8);
            this.m_Group.EnabledDynamicsValue = true;
            this.m_Group.Height = 368;
            this.m_Group.Left = 22;
            this.m_Group.Name = "m_Group";
            this.m_Group.ParentGroup = null;
            this.m_Group.ScreenOwnerName = "analogicas";
            this.m_Group.Top = 28;
            this.m_Group.VisibleDynamicsValue = true;
            this.m_Group.Width = 390;
            // 
            // m_CircularMeter
            // 
            this.m_CircularMeter.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_CircularMeter.BlinkDynamicsValue = false;
            this.m_CircularMeter.Clockwise = true;
            this.m_CircularMeter.EnabledDynamicsValue = true;
            this.m_CircularMeter.EndAngle = 300D;
            this.m_CircularMeter.ForceTransparency = false;
            this.m_CircularMeter.Height = 120;
            this.m_CircularMeter.IndicatorColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_CircularMeter.IndicatorLength = 35.1884D;
            this.m_CircularMeter.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(16.8D, 16.8D, 16.799999999999997D, 16.799999999999997D);
            this.m_CircularMeter.IndicatorWidth = 4.2000000000000028D;
            this.m_CircularMeter.InvalidateAtValueChanged = true;
            this.m_CircularMeter.Left = 142;
            this.m_CircularMeter.MajorTickCount = 11;
            this.m_CircularMeter.Maximum = 100D;
            this.m_CircularMeter.Minimum = 0D;
            this.m_CircularMeter.MinorTickCount = 4;
            this.m_CircularMeter.Name = "m_CircularMeter";
            this.m_CircularMeter.NeedleAnimation = true;
            this.m_CircularMeter.NeedleOscillations = false;
            this.m_CircularMeter.RequiresTransparency = true;
            this.m_CircularMeter.ScreenOwnerName = "analogicas";
            this.m_CircularMeter.ShortestPathAnimation = false;
            this.m_CircularMeter.StartAngle = 240D;
            this.m_CircularMeter.Top = 131;
            this.m_CircularMeter.VisibleDynamicsValue = true;
            this.m_CircularMeter.Width = 120;
            // 
            // m_Slider1
            // 
            this.m_Slider1.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider1.BlinkDynamicsValue = false;
            this.m_Slider1.EnabledDynamicsValue = true;
            this.m_Slider1.Focus = false;
            this.m_Slider1.FontSizePixels = 12;
            this.m_Slider1.ForceTransparency = false;
            this.m_Slider1.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider1.Height = 272;
            this.m_Slider1.IndicatorColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(144)))), ((int)(((byte)(238)))), ((int)(((byte)(144))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider1.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(9.5D, 14.687999999999988D, 29.150000000000006D, 14.687999999999988D);
            this.m_Slider1.InvalidateAtValueChanged = true;
            this.m_Slider1.Left = 498;
            this.m_Slider1.MajorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(9.5D, 14.687999999999988D, 47.825D, 14.687999999999988D);
            this.m_Slider1.MajorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(29.174999999999997D, 14.687999999999988D, 29.150000000000006D, 14.687999999999988D);
            this.m_Slider1.MajorTickCount = 11;
            this.m_Slider1.Maximum = 100D;
            this.m_Slider1.Minimum = 0D;
            this.m_Slider1.MinorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(14.5D, 14.687999999999988D, 48.825D, 14.687999999999988D);
            this.m_Slider1.MinorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(29.174999999999997D, 14.687999999999988D, 34.150000000000006D, 14.687999999999988D);
            this.m_Slider1.MinorTickCount = 1;
            this.m_Slider1.Name = "m_Slider1";
            this.m_Slider1.Orientation = Neo.ApplicationFramework.Controls.Controls.OrientationCF.Vertical;
            this.m_Slider1.RequiresTransparency = false;
            this.m_Slider1.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider1.ScreenOwnerName = "analogicas";
            this.m_Slider1.TextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(44.849999999999994D, 14.687999999999988D, 9.5D, 14.687999999999988D);
            this.m_Slider1.Top = 112;
            this.m_Slider1.VisibleDynamicsValue = true;
            this.m_Slider1.Width = 74;
            // 
            // m_Slider
            // 
            this.m_Slider.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider.BlinkDynamicsValue = false;
            this.m_Slider.EnabledDynamicsValue = true;
            this.m_Slider.Focus = false;
            this.m_Slider.FontSizePixels = 12;
            this.m_Slider.ForceTransparency = false;
            this.m_Slider.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider.Height = 272;
            this.m_Slider.IndicatorColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(165)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(9.5D, 14.687999999999988D, 29.150000000000006D, 14.687999999999988D);
            this.m_Slider.InvalidateAtValueChanged = true;
            this.m_Slider.Left = 645;
            this.m_Slider.MajorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(9.5D, 14.687999999999988D, 47.825D, 14.687999999999988D);
            this.m_Slider.MajorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(29.174999999999997D, 14.687999999999988D, 29.150000000000006D, 14.687999999999988D);
            this.m_Slider.MajorTickCount = 11;
            this.m_Slider.Maximum = 100D;
            this.m_Slider.Minimum = 0D;
            this.m_Slider.MinorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(14.5D, 14.687999999999988D, 48.825D, 14.687999999999988D);
            this.m_Slider.MinorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(29.174999999999997D, 14.687999999999988D, 34.150000000000006D, 14.687999999999988D);
            this.m_Slider.MinorTickCount = 1;
            this.m_Slider.Name = "m_Slider";
            this.m_Slider.Orientation = Neo.ApplicationFramework.Controls.Controls.OrientationCF.Vertical;
            this.m_Slider.RequiresTransparency = false;
            this.m_Slider.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Slider.ScreenOwnerName = "analogicas";
            this.m_Slider.TextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(44.849999999999994D, 14.687999999999988D, 9.5D, 14.687999999999988D);
            this.m_Slider.Top = 112;
            this.m_Slider.VisibleDynamicsValue = true;
            this.m_Slider.Width = 74;
            // 
            // m_LinearMeter
            // 
            this.m_LinearMeter.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_LinearMeter.BlinkDynamicsValue = false;
            brushdynamicsconvertercf1.BrushIntervalMapper.DefaultValue = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF();
            brushcfinterval1.End = 59D;
            brushcfinterval1.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(177)))), ((int)(((byte)(76))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval2.End = 79D;
            brushcfinterval2.Start = 60D;
            brushcfinterval2.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushcfinterval3.End = 100D;
            brushcfinterval3.Start = 80D;
            brushcfinterval3.Value = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Red, System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval1);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval2);
            brushdynamicsconvertercf1.BrushIntervalMapper.Intervals.Add(brushcfinterval3);
            this.m_LinearMeter.EnabledDynamicsValue = true;
            this.m_LinearMeter.FontSizePixels = 12;
            this.m_LinearMeter.ForceTransparency = false;
            this.m_LinearMeter.Foreground = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_LinearMeter.Height = 80;
            this.m_LinearMeter.IndicatorColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.Black, System.Drawing.Color.Black, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_LinearMeter.IndicatorMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(11.825000000000001D, 24.483333333333334D, 11.824999999999989D, 6D);
            this.m_LinearMeter.InvalidateAtValueChanged = true;
            this.m_LinearMeter.Left = 37;
            this.m_LinearMeter.MajorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(11.825000000000001D, 17.483333333333334D, 11.824999999999989D, 55.516666666666666D);
            this.m_LinearMeter.MajorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(double.NaN, double.NaN, double.NaN, double.NaN);
            this.m_LinearMeter.MajorTickCount = 11;
            this.m_LinearMeter.Maximum = 100D;
            this.m_LinearMeter.Minimum = 0D;
            this.m_LinearMeter.MinorScaleMarginFirst = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(11.825000000000001D, 19.483333333333334D, 11.824999999999989D, 55.516666666666666D);
            this.m_LinearMeter.MinorScaleMarginSecond = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(double.NaN, double.NaN, double.NaN, double.NaN);
            this.m_LinearMeter.MinorTickCount = 1;
            this.m_LinearMeter.Name = "m_LinearMeter";
            this.m_LinearMeter.Orientation = Neo.ApplicationFramework.Controls.Controls.OrientationCF.Horizontal;
            this.m_LinearMeter.RequiresTransparency = false;
            this.m_LinearMeter.ScaleColor = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_LinearMeter.ScreenOwnerName = "analogicas";
            this.m_LinearMeter.TextScaleMargin = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(2D, 3D, 2D, 62.516666666666666D);
            this.m_LinearMeter.Top = 305;
            this.m_LinearMeter.VisibleDynamicsValue = true;
            this.m_LinearMeter.Width = 358;
            // 
            // m_Text
            // 
            this.m_Text.BlinkDynamicsValue = false;
            this.m_Text.EnabledDynamicsValue = true;
            this.m_Text.FontSizePixels = 20;
            this.m_Text.Height = 28;
            this.m_Text.Left = 145;
            this.m_Text.Name = "m_Text";
            this.m_Text.ScreenOwnerName = "analogicas";
            this.m_Text.Top = 100;
            this.m_Text.VisibleDynamicsValue = true;
            this.m_Text.Width = 37;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 20;
            this.m_Text1.Height = 28;
            this.m_Text1.Left = 192;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "analogicas";
            this.m_Text1.Top = 277;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 37;
            // 
            // m_AnalogNumeric
            // 
            this.m_AnalogNumeric.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.FromArgb(((int)(((byte)(212)))), ((int)(((byte)(208)))), ((int)(((byte)(200))))), Neo.ApplicationFramework.Interfaces.FillDirection.VerticalBottomToTop);
            this.m_AnalogNumeric.BitmapEffect = new Neo.ApplicationFramework.Common.Graphics.Logic.BitmapEffectCF(2, 0, Neo.ApplicationFramework.Common.Graphics.Logic.LightAngle.LowerRight);
            this.m_AnalogNumeric.BlinkDynamicsValue = false;
            this.m_AnalogNumeric.BorderBrush = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(127)))), ((int)(((byte)(157)))), ((int)(((byte)(185))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_AnalogNumeric.BorderThickness = new Neo.ApplicationFramework.Common.Graphics.Logic.ThicknessCF(1D, 1D, 1D, 1D);
            this.m_AnalogNumeric.EnabledDynamicsValue = true;
            this.m_AnalogNumeric.FontSizePixels = 20;
            this.m_AnalogNumeric.Height = 30;
            this.m_AnalogNumeric.Left = 205;
            this.m_AnalogNumeric.LimitNumberOfCharacters = true;
            this.m_AnalogNumeric.MaxNumberOfCharacters = 3;
            this.m_AnalogNumeric.Name = "m_AnalogNumeric";
            this.m_AnalogNumeric.ReadOnly = true;
            this.m_AnalogNumeric.ScreenOwnerName = "analogicas";
            this.m_AnalogNumeric.Top = 100;
            this.m_AnalogNumeric.VisibleDynamicsValue = true;
            this.m_AnalogNumeric.Width = 54;
            // 
            // m_PolyLine1
            // 
            this.m_PolyLine1.BlinkDynamicsValue = false;
            this.m_PolyLine1.EnabledDynamicsValue = true;
            this.m_PolyLine1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(99)))), ((int)(((byte)(116))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine1.Height = 51;
            this.m_PolyLine1.Left = 509;
            this.m_PolyLine1.Name = "m_PolyLine1";
            this.m_PolyLine1.Points = new Neo.ApplicationFramework.Common.Collections.PointDList(new Neo.ApplicationFramework.Interfaces.PointD[] {
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(40.0781257805173D, 48.4999997971747D),
                        new Neo.ApplicationFramework.Interfaces.PointD(256.500004995311D, 48.4999997971747D),
                        new Neo.ApplicationFramework.Interfaces.PointD(256.500004995311D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D)});
            this.m_PolyLine1.ScreenOwnerName = "analogicas";
            this.m_PolyLine1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine1.Top = 28;
            this.m_PolyLine1.VisibleDynamicsValue = true;
            this.m_PolyLine1.Width = 259;
            // 
            // m_Text3
            // 
            this.m_Text3.BlinkDynamicsValue = false;
            this.m_Text3.EnabledDynamicsValue = true;
            this.m_Text3.FontSizePixels = 20;
            this.m_Text3.Height = 28;
            this.m_Text3.Left = 509;
            this.m_Text3.Name = "m_Text3";
            this.m_Text3.ScreenOwnerName = "analogicas";
            this.m_Text3.Top = 86;
            this.m_Text3.VisibleDynamicsValue = true;
            this.m_Text3.Width = 39;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 20;
            this.m_Text2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text2.Height = 28;
            this.m_Text2.Left = 558;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "analogicas";
            this.m_Text2.Top = 37;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 140;
            // 
            // m_Text4
            // 
            this.m_Text4.BlinkDynamicsValue = false;
            this.m_Text4.EnabledDynamicsValue = true;
            this.m_Text4.FontSizePixels = 20;
            this.m_Text4.Height = 28;
            this.m_Text4.Left = 655;
            this.m_Text4.Name = "m_Text4";
            this.m_Text4.ScreenOwnerName = "analogicas";
            this.m_Text4.Top = 86;
            this.m_Text4.VisibleDynamicsValue = true;
            this.m_Text4.Width = 39;
            // 
            // m_Text6
            // 
            this.m_Text6.BlinkDynamicsValue = false;
            this.m_Text6.EnabledDynamicsValue = true;
            this.m_Text6.FontSizePixels = 20;
            this.m_Text6.Height = 28;
            this.m_Text6.Left = 258;
            this.m_Text6.Name = "m_Text6";
            this.m_Text6.ScreenOwnerName = "analogicas";
            this.m_Text6.Top = 100;
            this.m_Text6.VisibleDynamicsValue = true;
            this.m_Text6.Width = 24;
            // 
            // m_PolyLine2
            // 
            this.m_PolyLine2.BlinkDynamicsValue = false;
            this.m_PolyLine2.EnabledDynamicsValue = true;
            this.m_PolyLine2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(99)))), ((int)(((byte)(116))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine2.Height = 66;
            this.m_PolyLine2.Left = 0;
            this.m_PolyLine2.Name = "m_PolyLine2";
            this.m_PolyLine2.Points = new Neo.ApplicationFramework.Common.Collections.PointDList(new Neo.ApplicationFramework.Interfaces.PointD[] {
                        new Neo.ApplicationFramework.Interfaces.PointD(49.6666666666667D, 0.44709646730081D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 63.6154566858273D),
                        new Neo.ApplicationFramework.Interfaces.PointD(255D, 62.7318718426511D),
                        new Neo.ApplicationFramework.Interfaces.PointD(254.111111111111D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(49.6666666666667D, 0.44709646730081D)});
            this.m_PolyLine2.ScreenOwnerName = "analogicas";
            this.m_PolyLine2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine2.Top = 0;
            this.m_PolyLine2.VisibleDynamicsValue = true;
            this.m_PolyLine2.Width = 257;
            // 
            // m_Text5
            // 
            this.m_Text5.BlinkDynamicsValue = false;
            this.m_Text5.EnabledDynamicsValue = true;
            this.m_Text5.FontSizePixels = 24;
            this.m_Text5.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text5.Height = 28;
            this.m_Text5.Left = 101;
            this.m_Text5.Name = "m_Text5";
            this.m_Text5.ScreenOwnerName = "analogicas";
            this.m_Text5.Top = 17;
            this.m_Text5.VisibleDynamicsValue = true;
            this.m_Text5.Width = 55;
            // 
            // m_Group1
            // 
            this.m_Group1.BlinkDynamicsValue = false;
            this.m_Group1.Components.Add(this.m_PolyLine2);
            this.m_Group1.Components.Add(this.m_Text5);
            this.m_Group1.EnabledDynamicsValue = true;
            this.m_Group1.Height = 64;
            this.m_Group1.Left = 547;
            this.m_Group1.Name = "m_Group1";
            this.m_Group1.ParentGroup = null;
            this.m_Group1.ScreenOwnerName = "analogicas";
            this.m_Group1.Top = 417;
            this.m_Group1.VisibleDynamicsValue = true;
            this.m_Group1.Width = 255;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "analogicas";
            this.PopupScreen = false;
            this.ScreenID = ((ushort)(120));
            this.ScreenTitle = "analogIO";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_analogicas = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_analogicas) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Ellipse1);
            this.DrawingPrimitives.Add(this.m_Rectangle1);
            this.DrawingPrimitives.Add(this.m_Rectangle);
            this.DrawingPrimitives.Add(this.m_PolyLine);
            this.DrawingPrimitives.Add(this.m_Text8);
            this.DrawingPrimitives.Add(this.m_Group);
            this.DrawingPrimitives.Add(this.m_CircularMeter);
            this.DrawingPrimitives.Add(this.m_Slider1);
            this.DrawingPrimitives.Add(this.m_Slider);
            this.DrawingPrimitives.Add(this.m_LinearMeter);
            this.DrawingPrimitives.Add(this.m_Text);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_AnalogNumeric);
            this.DrawingPrimitives.Add(this.m_PolyLine1);
            this.DrawingPrimitives.Add(this.m_Text3);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Text4);
            this.DrawingPrimitives.Add(this.m_Text6);
            this.DrawingPrimitives.Add(this.m_PolyLine2);
            this.DrawingPrimitives.Add(this.m_Text5);
            this.DrawingPrimitives.Add(this.m_Group1);
            ((System.ComponentModel.ISupportInitialize)(this.m_Text8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_CircularMeter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Slider1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Slider)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_LinearMeter)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_AnalogNumeric)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).EndInit();
        }
        
        private void m_Slider1_Action_ValueChanged(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Slider1", "ValueChanged", "Set Analog", "Tags.AO0", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AO0.SetAnalog(100);
        }
        
        private void m_Slider_Action_ValueChanged(object sender, System.EventArgs e) {
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Slider", "ValueChanged", "Set Analog", "Tags.AO1", "");
            Neo.ApplicationFramework.Generated.Globals.Tags.AO1.SetAnalog(100);
        }
        
        private void m_Group1_Action_MouseEnter(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Group1", "MouseEnter", "Show Screen", "inicio", "");
            Neo.ApplicationFramework.Generated.Globals.inicio.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(analogicas));
            this.m_Text2.Text = resources.GetText("analogicas.Text2.Text", "Saídas Analógicas");
            this.m_Text8.Text = resources.GetText("analogicas.Text8.Text", "Entradas Analógicas");
            this.m_Text.Text = resources.GetText("analogicas.Text.Text", "AV0");
            this.m_Text1.Text = resources.GetText("analogicas.Text1.Text", "AV1");
            this.m_Text3.Text = resources.GetText("analogicas.Text3.Text", "AO0");
            this.m_Text4.Text = resources.GetText("analogicas.Text4.Text", "AO1");
            this.m_Text5.Text = resources.GetText("analogicas.Text5.Text", "TB131");
            this.m_Text6.Text = resources.GetText("analogicas.Text6.Text", "%");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_analogicas) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding1 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.AV1"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_LinearMeter.DataBindings.Add(dynamicBinding1);
            this.m_DynamicBindings.Add(dynamicBinding1);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding2 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("IndicatorColor", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.AV1"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, brushdynamicsconvertercf1);
            this.m_LinearMeter.DataBindings.Add(dynamicBinding2);
            this.m_DynamicBindings.Add(dynamicBinding2);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding3 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.AV0"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_AnalogNumeric.DataBindings.Add(dynamicBinding3);
            this.m_DynamicBindings.Add(dynamicBinding3);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding4 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.AV0"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_CircularMeter.DataBindings.Add(dynamicBinding4);
            this.m_DynamicBindings.Add(dynamicBinding4);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding5 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.AO0"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Slider1.DataBindings.Add(dynamicBinding5);
            this.m_DynamicBindings.Add(dynamicBinding5);
            Neo.ApplicationFramework.Common.Data.DynamicBinding dynamicBinding6 = new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateProxy("Tags.AO1"), "Value", true, System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged, Neo.ApplicationFramework.Common.Dynamics.VariantValueConverterCF.Default);
            this.m_Slider.DataBindings.Add(dynamicBinding6);
            this.m_DynamicBindings.Add(dynamicBinding6);
        }
    }
}
