//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated {
    using Neo.ApplicationFramework.Controls.Controls;
    using Neo.ApplicationFramework.Controls;
    using Neo.ApplicationFramework.Interfaces;
    using Neo.ApplicationFramework.Tools.Security;
    using Neo.ApplicationFramework.Tools.Actions;
    using Neo.ApplicationFramework.Common.MultiLanguage;
    
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class duo_tb131 : Neo.ApplicationFramework.Controls.Controls.Form {
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture;
        
        private Neo.ApplicationFramework.Controls.Symbol.PictureCF m_Picture1;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line1;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse1;
        
        private Neo.ApplicationFramework.Controls.Controls.EllipseCF m_Ellipse2;
        
        private Neo.ApplicationFramework.Controls.Controls.Line m_Line4;
        
        private Neo.ApplicationFramework.Controls.Controls.PolylineCF m_PolyLine3;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text2;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group;
        
        private Neo.ApplicationFramework.Controls.Controls.PolylineCF m_PolyLine;
        
        private Neo.ApplicationFramework.Controls.Controls.Label m_Text1;
        
        private Neo.ApplicationFramework.Controls.Controls.GroupCF m_Group1;
        
        private bool m_Initialized_duo_tb131;
        
        public duo_tb131() {
            this.InitializeComponent();
            this.m_Picture1.MouseEnter += new System.EventHandler(this.m_Picture1_Action_MouseEnter);
            this.m_Group.MouseEnter += new System.EventHandler(this.m_Group_Action_MouseEnter);
            this.m_PolyLine3.MouseEnter += new System.EventHandler(this.m_PolyLine3_Action_MouseEnter);
            this.m_Text2.MouseEnter += new System.EventHandler(this.m_Text2_Action_MouseEnter);
            this.m_Group1.MouseEnter += new System.EventHandler(this.m_Group1_Action_MouseEnter);
            this.ApplyLanguageInitialize();
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter Picture1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableCFAdapter>(this.m_Picture1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter Ellipse2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ShapeCFAdapter>(this.m_Ellipse2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.LineCFAdapter Line4 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.LineCFAdapter>(this.m_Line4);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter PolyLine3 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter>(this.m_PolyLine3);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text2 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text2);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.GroupCFAdapter Group1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.GroupCFAdapter>(this.m_Group1);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter PolyLine {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.PolylineCFAdapter>(this.m_PolyLine);
            }
        }
        
        protected Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter Text1 {
            get {
                return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextControlCFAdapter>(this.m_Text1);
            }
        }
        
        private void InitializeComponent() {
            this.m_Picture = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Picture1 = new Neo.ApplicationFramework.Controls.Symbol.PictureCF();
            this.m_Line1 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_Ellipse1 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Ellipse2 = new Neo.ApplicationFramework.Controls.Controls.EllipseCF();
            this.m_Line4 = new Neo.ApplicationFramework.Controls.Controls.Line();
            this.m_PolyLine3 = new Neo.ApplicationFramework.Controls.Controls.PolylineCF();
            this.m_Text2 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Group = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            this.m_PolyLine = new Neo.ApplicationFramework.Controls.Controls.PolylineCF();
            this.m_Text1 = new Neo.ApplicationFramework.Controls.Controls.Label();
            this.m_Group1 = new Neo.ApplicationFramework.Controls.Controls.GroupCF();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).BeginInit();
            this.SuspendLayout();
            // 
            // duo_tb131
            // 
            this.Background = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.BorderStyle = Neo.ApplicationFramework.Interfaces.ScreenBorderStyle.SingleBorder;
            this.ControlBox = false;
            // 
            // m_Picture
            // 
            this.m_Picture.BlinkDynamicsValue = false;
            this.m_Picture.EnabledDynamicsValue = true;
            this.m_Picture.Height = 349;
            this.m_Picture.Left = 306;
            this.m_Picture.Name = "m_Picture";
            this.m_Picture.ScreenOwnerName = "duo_tb131";
            this.m_Picture.Stretch = true;
            this.m_Picture.SymbolName = "trainingboxduo-tb131 (1)";
            this.m_Picture.Top = 30;
            this.m_Picture.VisibleDynamicsValue = true;
            this.m_Picture.Width = 491;
            // 
            // m_Picture1
            // 
            this.m_Picture1.BlinkDynamicsValue = false;
            this.m_Picture1.EnabledDynamicsValue = true;
            this.m_Picture1.Height = 114;
            this.m_Picture1.Left = -1;
            this.m_Picture1.Name = "m_Picture1";
            this.m_Picture1.ScreenOwnerName = "duo_tb131";
            this.m_Picture1.Stretch = true;
            this.m_Picture1.SymbolName = "logo-ifsp";
            this.m_Picture1.Top = 365;
            this.m_Picture1.VisibleDynamicsValue = true;
            this.m_Picture1.Width = 319;
            // 
            // m_Line1
            // 
            this.m_Line1.BlinkDynamicsValue = false;
            this.m_Line1.EnabledDynamicsValue = true;
            this.m_Line1.Fill = null;
            this.m_Line1.Name = "m_Line1";
            this.m_Line1.ScreenOwnerName = "duo_tb131";
            this.m_Line1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line1.StrokeThickness = 5;
            this.m_Line1.VisibleDynamicsValue = true;
            this.m_Line1.X1 = 335;
            this.m_Line1.X2 = 284;
            this.m_Line1.Y1 = 231;
            this.m_Line1.Y2 = 232;
            // 
            // m_Ellipse1
            // 
            this.m_Ellipse1.BlinkDynamicsValue = false;
            this.m_Ellipse1.EnabledDynamicsValue = true;
            this.m_Ellipse1.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(71)))), ((int)(((byte)(122))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Height = 15;
            this.m_Ellipse1.Left = 334;
            this.m_Ellipse1.Name = "m_Ellipse1";
            this.m_Ellipse1.ScreenOwnerName = "duo_tb131";
            this.m_Ellipse1.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse1.Top = 224;
            this.m_Ellipse1.VisibleDynamicsValue = true;
            this.m_Ellipse1.Width = 15;
            // 
            // m_Ellipse2
            // 
            this.m_Ellipse2.BlinkDynamicsValue = false;
            this.m_Ellipse2.EnabledDynamicsValue = true;
            this.m_Ellipse2.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(71)))), ((int)(((byte)(122))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Height = 15;
            this.m_Ellipse2.Left = 335;
            this.m_Ellipse2.Name = "m_Ellipse2";
            this.m_Ellipse2.ScreenOwnerName = "duo_tb131";
            this.m_Ellipse2.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Ellipse2.Top = 179;
            this.m_Ellipse2.VisibleDynamicsValue = true;
            this.m_Ellipse2.Width = 15;
            // 
            // m_Line4
            // 
            this.m_Line4.BlinkDynamicsValue = false;
            this.m_Line4.EnabledDynamicsValue = true;
            this.m_Line4.Fill = null;
            this.m_Line4.Name = "m_Line4";
            this.m_Line4.ScreenOwnerName = "duo_tb131";
            this.m_Line4.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_Line4.StrokeThickness = 5;
            this.m_Line4.VisibleDynamicsValue = true;
            this.m_Line4.X1 = 336;
            this.m_Line4.X2 = 285;
            this.m_Line4.Y1 = 186;
            this.m_Line4.Y2 = 186;
            // 
            // m_PolyLine3
            // 
            this.m_PolyLine3.BlinkDynamicsValue = false;
            this.m_PolyLine3.EnabledDynamicsValue = true;
            this.m_PolyLine3.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(99)))), ((int)(((byte)(116))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine3.Height = 67;
            this.m_PolyLine3.Left = 0;
            this.m_PolyLine3.Name = "m_PolyLine3";
            this.m_PolyLine3.Points = new Neo.ApplicationFramework.Common.Collections.PointDList(new Neo.ApplicationFramework.Interfaces.PointD[] {
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0.999999999999986D, 64.5016935518598D),
                        new Neo.ApplicationFramework.Interfaces.PointD(256D, 63.6181087086836D),
                        new Neo.ApplicationFramework.Interfaces.PointD(209.333333333333D, 0.441792421588131D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D)});
            this.m_PolyLine3.ScreenOwnerName = "duo_tb131";
            this.m_PolyLine3.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine3.StrokeThickness = 3;
            this.m_PolyLine3.Top = 0;
            this.m_PolyLine3.VisibleDynamicsValue = true;
            this.m_PolyLine3.Width = 258;
            // 
            // m_Text2
            // 
            this.m_Text2.BlinkDynamicsValue = false;
            this.m_Text2.EnabledDynamicsValue = true;
            this.m_Text2.FontSizePixels = 24;
            this.m_Text2.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text2.Height = 28;
            this.m_Text2.Left = 68;
            this.m_Text2.Name = "m_Text2";
            this.m_Text2.ScreenOwnerName = "duo_tb131";
            this.m_Text2.Top = 15;
            this.m_Text2.VisibleDynamicsValue = true;
            this.m_Text2.Width = 62;
            // 
            // m_Group
            // 
            this.m_Group.BlinkDynamicsValue = false;
            this.m_Group.Components.Add(this.m_PolyLine3);
            this.m_Group.Components.Add(this.m_Text2);
            this.m_Group.EnabledDynamicsValue = true;
            this.m_Group.Height = 65;
            this.m_Group.Left = 33;
            this.m_Group.Name = "m_Group";
            this.m_Group.ParentGroup = null;
            this.m_Group.ScreenOwnerName = "duo_tb131";
            this.m_Group.Top = 124;
            this.m_Group.VisibleDynamicsValue = true;
            this.m_Group.Width = 256;
            // 
            // m_PolyLine
            // 
            this.m_PolyLine.BlinkDynamicsValue = false;
            this.m_PolyLine.EnabledDynamicsValue = true;
            this.m_PolyLine.Fill = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(99)))), ((int)(((byte)(116))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine.Height = 65;
            this.m_PolyLine.Left = 0;
            this.m_PolyLine.Name = "m_PolyLine";
            this.m_PolyLine.Points = new Neo.ApplicationFramework.Common.Collections.PointDList(new Neo.ApplicationFramework.Interfaces.PointD[] {
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(256D, 0D),
                        new Neo.ApplicationFramework.Interfaces.PointD(208D, 63D),
                        new Neo.ApplicationFramework.Interfaces.PointD(1D, 63D),
                        new Neo.ApplicationFramework.Interfaces.PointD(0D, 0D)});
            this.m_PolyLine.ScreenOwnerName = "duo_tb131";
            this.m_PolyLine.Stroke = new Neo.ApplicationFramework.Common.Graphics.Logic.BrushCF(System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), System.Drawing.Color.Empty, Neo.ApplicationFramework.Interfaces.FillDirection.None);
            this.m_PolyLine.StrokeThickness = 3;
            this.m_PolyLine.Top = 0;
            this.m_PolyLine.VisibleDynamicsValue = true;
            this.m_PolyLine.Width = 258;
            // 
            // m_Text1
            // 
            this.m_Text1.BlinkDynamicsValue = false;
            this.m_Text1.EnabledDynamicsValue = true;
            this.m_Text1.FontSizePixels = 24;
            this.m_Text1.Foreground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.m_Text1.Height = 28;
            this.m_Text1.Left = 46;
            this.m_Text1.Name = "m_Text1";
            this.m_Text1.ScreenOwnerName = "duo_tb131";
            this.m_Text1.TextHorizontalAlignment = "Center";
            this.m_Text1.TextVerticalAlignment = "Center";
            this.m_Text1.Top = 14;
            this.m_Text1.VisibleDynamicsValue = true;
            this.m_Text1.Width = 87;
            // 
            // m_Group1
            // 
            this.m_Group1.BlinkDynamicsValue = false;
            this.m_Group1.Components.Add(this.m_PolyLine);
            this.m_Group1.Components.Add(this.m_Text1);
            this.m_Group1.EnabledDynamicsValue = true;
            this.m_Group1.Height = 63;
            this.m_Group1.Left = 33;
            this.m_Group1.Name = "m_Group1";
            this.m_Group1.ParentGroup = null;
            this.m_Group1.ScreenOwnerName = "duo_tb131";
            this.m_Group1.Top = 231;
            this.m_Group1.VisibleDynamicsValue = true;
            this.m_Group1.Width = 256;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.ClientSize = new System.Drawing.Size(800, 480);
            this.IsCacheable = true;
            this.Location = new System.Drawing.Point(0, 0);
            this.ModalScreen = true;
            this.Name = "duo_tb131";
            this.PopupScreen = false;
            this.ScreenID = ((ushort)(100));
            this.ScreenTitle = "kit_didatico";
            this.StyleName = "";
            this.WindowState = System.Windows.Forms.FormWindowState.Normal;
            this.m_Initialized_duo_tb131 = true;
            this.AddControlsAndPrimitives();
            this.ResumeLayout(false);
        }
        
        protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData() {
            System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
            instanceList.Add(this.CreateInstanceData_Default());
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
            aliasInstances.Instances = instanceList.ToArray();
            return aliasInstances;
        }
        
        private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default() {
            Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF aliasinstancecf1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
            aliasinstancecf1.Name = "Default";
            aliasinstancecf1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
            return aliasinstancecf1;
        }
        
        protected override void BindAliases() {
        }
        
        protected override void Dispose(bool disposing) {
            base.Dispose(disposing);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControlsAndPrimitives() {
            if (!m_Initialized_duo_tb131) {
                return;
            }
            this.AddControls();
            this.AddDrawingPrimitives();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddControls() {
            base.AddControls();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void AddDrawingPrimitives() {
            base.AddDrawingPrimitives();
            this.DrawingPrimitives.Add(this.m_Picture);
            this.DrawingPrimitives.Add(this.m_Picture1);
            this.DrawingPrimitives.Add(this.m_Line1);
            this.DrawingPrimitives.Add(this.m_Ellipse1);
            this.DrawingPrimitives.Add(this.m_Ellipse2);
            this.DrawingPrimitives.Add(this.m_Line4);
            this.DrawingPrimitives.Add(this.m_PolyLine3);
            this.DrawingPrimitives.Add(this.m_Text2);
            this.DrawingPrimitives.Add(this.m_Group);
            this.DrawingPrimitives.Add(this.m_PolyLine);
            this.DrawingPrimitives.Add(this.m_Text1);
            this.DrawingPrimitives.Add(this.m_Group1);
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Picture1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Text1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.m_Group1)).EndInit();
        }
        
        private void m_Picture1_Action_MouseEnter(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Picture1", "MouseEnter", "Show Screen", "inicio", "Default", "");
            Neo.ApplicationFramework.Generated.Globals.inicio.Show();
        }
        
        private void m_Group_Action_MouseEnter(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Group", "MouseEnter", "Show Screen", "digitais", "");
            Neo.ApplicationFramework.Generated.Globals.digitais.Show();
        }
        
        private void m_PolyLine3_Action_MouseEnter(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_PolyLine3", "MouseEnter", "Show Screen", "digitais", "");
            Neo.ApplicationFramework.Generated.Globals.digitais.Show();
        }
        
        private void m_Text2_Action_MouseEnter(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Text2", "MouseEnter", "Show Screen", "digitais", "");
            Neo.ApplicationFramework.Generated.Globals.digitais.Show();
        }
        
        private void m_Group1_Action_MouseEnter(object sender, System.EventArgs e) {
            if (this.IsSecurityAccessDeniedOnEvent(sender, e)) {
                return;
            }
            Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Group1", "MouseEnter", "Show Screen", "analogicas", "");
            Neo.ApplicationFramework.Generated.Globals.analogicas.Show();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        private void ApplyLanguageInternal() {
            Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(duo_tb131));
            this.m_Text2.Text = resources.GetText("duo_tb131.Text2.Text", "Digitais");
            this.m_Text1.Text = resources.GetText("duo_tb131.Text1.Text", "Analógicas");
            this.ApplyResourcesOnForm();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void ApplyLanguage() {
            if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated) {
                return;
            }
            this.ApplyLanguageInternal();
            base.ApplyLanguage();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ApplyLanguageInitialize() {
            if (!m_Initialized_duo_tb131) {
                return;
            }
            base.ApplyLanguageInitialize();
            this.ApplyLanguageInternal();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public override void ConnectDataBindings() {
            base.ConnectDataBindings();
        }
    }
}
