//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class Tags : Neo.ApplicationFramework.Tools.OpcClient.GlobalController
	{
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag S0;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag S1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag S2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag S3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem E0;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem E1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem E2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem E3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem AV0;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem AV1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem AO0;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem AO1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag S4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag S5;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag S6;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag S7;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem E4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem E5;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem E6;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem E7;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup5;
		
		public Tags()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.S0 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("S0", "TB131_Modbus.DataItem1", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.S1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("S1", "TB131_Modbus.DataItem2", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.S2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("S2", "TB131_Modbus.DataItem3", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.S3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("S3", "TB131_Modbus.DataItem4", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.E0 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("E0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.E1 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("E1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.E2 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("E2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.E3 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("E3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.AV0 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("AV0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_UINTEGER2)), "", ((short)(1)), "", "");
			this.AV1 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("AV1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_UINTEGER2)), "", ((short)(1)), "", "");
			this.AO0 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("AO0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Write, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_UINTEGER2)), "", ((short)(1)), "", "");
			this.AO1 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("AO1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Write, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_UINTEGER2)), "", ((short)(1)), "", "");
			this.S4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("S4", "TB131_Modbus.DataItem5", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.S5 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("S5", "TB131_Modbus.DataItem6", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.S6 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("S6", "TB131_Modbus.DataItem7", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.S7 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("S7", "TB131_Modbus.DataItem8", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), false, "", null);
			this.E4 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("E4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.E5 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("E5", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.E6 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("E6", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.E7 = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("E7", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false, "Value Change", Neo.ApplicationFramework.Interfaces.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BOOLEAN)), "", ((short)(1)), "", "");
			this.PollGroup1 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup2 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup3 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup4 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup5 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.E0.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem9"}, true));
			this.E1.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem10"}, true));
			this.E2.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem11"}, true));
			this.E3.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem12"}, true));
			this.AV0.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem17"}, true));
			this.AV1.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem18"}, true));
			this.AO0.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem19"}, true));
			this.AO1.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem20"}, true));
			this.E4.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem13"}, true));
			this.E5.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem14"}, true));
			this.E6.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem15"}, true));
			this.E7.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"TB131_Modbus"}, new string[] {
							"DataItem16"}, true));
			this.LightweightTags.Add(this.S0);
			this.LightweightTags.Add(this.S1);
			this.LightweightTags.Add(this.S2);
			this.LightweightTags.Add(this.S3);
			this.GlobalDataItems.Add(this.E0);
			this.GlobalDataItems.Add(this.E1);
			this.GlobalDataItems.Add(this.E2);
			this.GlobalDataItems.Add(this.E3);
			this.GlobalDataItems.Add(this.AV0);
			this.GlobalDataItems.Add(this.AV1);
			this.GlobalDataItems.Add(this.AO0);
			this.GlobalDataItems.Add(this.AO1);
			this.LightweightTags.Add(this.S4);
			this.LightweightTags.Add(this.S5);
			this.LightweightTags.Add(this.S6);
			this.LightweightTags.Add(this.S7);
			this.GlobalDataItems.Add(this.E4);
			this.GlobalDataItems.Add(this.E5);
			this.GlobalDataItems.Add(this.E6);
			this.GlobalDataItems.Add(this.E7);
			this.PollGroup1.Interval = 500;
			this.PollGroup1.Name = "PollGroup1";
			this.PollGroup2.Interval = 500;
			this.PollGroup2.Name = "PollGroup2";
			this.PollGroup3.Interval = 500;
			this.PollGroup3.Name = "PollGroup3";
			this.PollGroup4.Interval = 500;
			this.PollGroup4.Name = "PollGroup4";
			this.PollGroup5.Interval = 500;
			this.PollGroup5.Name = "PollGroup5";
			this.PollGroups.Add(this.PollGroup1);
			this.PollGroups.Add(this.PollGroup2);
			this.PollGroups.Add(this.PollGroup3);
			this.PollGroups.Add(this.PollGroup4);
			this.PollGroups.Add(this.PollGroup5);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Tags));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
